[build]
  base = "/"
  command = "composer install && npm install && npm run build && php artisan config:cache && php artisan route:cache"
  publish = "public"

[[redirects]]
  from = "/{any}"
  to = "/index.php"
  status = 200
  force = true
